language: python
python:
  - "3.6"
services:
  - docker

before_script:
  - docker-compose build app sh -c "python manage.py test && flake8"
#  - docker-compose run app sh -c "python manage.py test && flake8"
#    WARNING: Image for service app was built because it did not already exist.
#    To rebuild this image you must use `docker-compose build` or
#    `docker-compose up --build`.